version: 2.1
orbs:
  # Circle Node orb makes it simple to cache dependencies
  # https://circleci.com/orbs/registry/orb/circleci/node
  node: circleci/node@1.1
  # Cypress orb makes it simple to install, cache and run Cypress tests
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1

commands:
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  load_workspace:
    steps:
      - attach_workspace:
          at: ~/

jobs:
  build:
    executor: cypress/base-12
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: install dependencies 📦
                command: npm ci
      - save_workspace
      - run:
          name: run tests 🧪
          command: npm test

  test-4:
    executor: cypress/base-12
    working_directory: ~/repo
    steps:
      - load_workspace
      - run:
          name: Test scaffolding Cypress v4
          environment:
            DEBUG: '@bahmutov/cly'
          command: |
            mkdir /tmp/test-4
            cd /tmp/test-4
            npm init -y
            npm i -D cypress@4
            node ~/repo/src/index.js init

  release:
    executor: cypress/base-12
    working_directory: ~/repo
    steps:
      - load_workspace
      - run:
          name: NPM publish 🚀
          command: npm run semantic-release


workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test-4:
        requires:
          - build
    - release:
        requires:
          - build
          - test-4
