version: 2.1
orbs:
  # Circle Node orb makes it simple to cache dependencies
  # https://circleci.com/orbs/registry/orb/circleci/node
  node: circleci/node@1.1
  # Cypress orb makes it simple to install, cache and run Cypress tests
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1
jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: install dependencies 📦
                command: npm ci
      - run:
          name: run tests 🧪
          command: npm test
      - run:
          name: NPM publish 🚀
          command: npm run semantic-release
workflows:
  version: 2
  workflow:
    jobs:
    - build
