name: ci
on:
  push:
    branches:
      - master
jobs:
  test-default:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.7.0

      - name: Print files 🖨
        run: ls -la

      - name: Print Node version 🖨
        run: node -v

      - name: Print NPM version 🖨
        run: npm -v

      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1.12.1

      - name: Run tests 🧪
        run: npm test

      - name: Run e2e test 🚀
        run: |
          echo $PWD
          mkdir /tmp/test-repo
          cd /tmp/test-repo
          npm init -y
          npm i -D cypress
          npm i cypress-expect
          node /home/runner/work/cly/cly/src/index.js init
          npx cypress-expect run --passing 1

  test-bare:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.7.0

      - name: Print files 🖨
        run: ls -la

      - name: Print Node version 🖨
        run: node -v

      - name: Print NPM version 🖨
        run: npm -v

      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1.12.1

      - name: Run tests 🧪
        run: npm test

      - name: Run e2e test with --bare 🚀
        run: |
          echo $PWD
          mkdir /tmp/test-bare
          cd /tmp/test-bare
          npm init -y
          npm i -D cypress
          npm i cypress-expect
          node /home/runner/work/cly/cly/src/index.js init --bare
          cat cypress.config.js
          npx cypress-expect run --passing 1

  release:
    runs-on: ubuntu-20.04
    needs: [test-default, test-bare]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.7.0

      - name: Print files 🖨
        run: ls -la

      - name: Print Node version 🖨
        run: node -v

      - name: Print NPM version 🖨
        run: npm -v

      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1.12.1

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
